# Generated by Django 5.0.1 on 2024-02-19 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs')),
                ('title', models.CharField(max_length=23)),
            ],
        ),
        migrations.CreateModel(
            name='FilePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=80)),
                ('subheading', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('file_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafedra.filemodel')),
            ],
        ),
    ]
