# Generated by Django 5.0.1 on 2024-02-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafedra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepage',
            name='file_list',
        ),
        migrations.AddField(
            model_name='filepage',
            name='file_list',
            field=models.ManyToManyField(to='cafedra.filemodel'),
        ),
    ]
