# Generated by Django 5.0.1 on 2024-02-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafedra', '0002_remove_filepage_file_list_filepage_file_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pdf_file',
            field=models.FileField(upload_to='static/cafedra/pdfs/'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to='static/cafedra/pdfs/'),
        ),
        migrations.AlterField(
            model_name='filepage',
            name='heading',
            field=models.CharField(max_length=80, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='filepage',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='слег-сайта'),
        ),
        migrations.AlterField(
            model_name='filepage',
            name='subheading',
            field=models.CharField(max_length=150, verbose_name='Под загаловок'),
        ),
    ]
