# Generated by Django 5.0.1 on 2024-02-21 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafedra', '0003_alter_employee_pdf_file_alter_filemodel_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to='static/cafedra/pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
