# Generated by Django 5.0.1 on 2024-02-21 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafedra', '0004_alter_filemodel_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=80, verbose_name='Заголовок')),
                ('subheader', models.CharField(max_length=150, verbose_name='Под загаловок')),
                ('img', models.FileField(upload_to='static/cafedra/header_img/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
            ],
        ),
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=80, verbose_name='Заголовок')),
                ('subheader', models.CharField(max_length=150, verbose_name='Под загаловок')),
                ('ingo_text', models.TextField()),
                ('header_img', models.FileField(upload_to='static/cafedra/header_img/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='pdf_file',
            field=models.FileField(upload_to='static/cafedra/pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
