# Generated by Django 5.0.1 on 2024-02-22 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafedra', '0005_employeepage_infopage_alter_employee_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.FileField(default='static/cafedra/img/cat2.png', upload_to='static/cafedra/header_img/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='employee',
            name='specialization',
            field=models.CharField(default='...', max_length=1000),
        ),
    ]
