# Generated by Django 5.0.1 on 2024-02-22 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafedra', '0006_employee_photo_employee_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepage',
            name='employes_list',
            field=models.ManyToManyField(to='cafedra.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.FileField(upload_to='static/cafedra/header_img/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='specialization',
            field=models.CharField(max_length=1000),
        ),
    ]
