# Generated by Django 5.0.1 on 2024-02-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafedra', '0007_employeepage_employes_list_alter_employee_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepage',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='слег-сайта'),
        ),
    ]
