# Generated by Django 5.0.1 on 2024-02-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafedra', '0008_employeepage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='слег-сайта'),
        ),
    ]
