# Generated by Django 4.2.5 on 2024-02-24 21:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafedra', '0010_filepage_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='ingo_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
