# Generated by Django 5.0.1 on 2024-02-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafedra', '0012_employeepage_page_name_filepage_page_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infopage',
            old_name='ingo_text',
            new_name='info_text',
        ),
    ]
