# Generated by Django 5.0.1 on 2024-02-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafedra', '0013_rename_ingo_text_infopage_info_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_university', models.CharField(max_length=75)),
                ('head_department', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=30)),
                ('short_info', models.CharField(max_length=300)),
                ('slug_for_summary', models.SlugField(unique=True, verbose_name='слег-резюме')),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(default='+996 222-31-01-61', max_length=15)),
                ('email', models.CharField(max_length=40)),
                ('photo', models.ImageField(upload_to='static/main_img/')),
            ],
        ),
    ]
