# Generated by Django 5.0.1 on 2024-02-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafedra', '0014_mainpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpage',
            old_name='head_department',
            new_name='name',
        ),
    ]
