# Generated by Django 5.0.1 on 2024-02-25 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafedra', '0015_rename_head_department_mainpage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='photo_deportament',
            field=models.FileField(default='static/cafedra/header_img/bg.jpg', upload_to='static/main_img/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
