# Generated by Django 5.0.1 on 2024-02-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafedra', '0016_mainpage_photo_deportament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='phone_number',
            field=models.CharField(default='+996 222-31-01-61', max_length=25),
        ),
    ]
