# Generated by Django 5.0.1 on 2024-02-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafedra', '0017_alter_mainpage_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='slug_for_summary',
            field=models.CharField(max_length=100, verbose_name='слег-резюме'),
        ),
    ]
