# Generated by Django 5.0.1 on 2024-02-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafedra', '0018_alter_mainpage_slug_for_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpage',
            old_name='slug_for_summary',
            new_name='summary',
        ),
    ]
